/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PSingleAssetJoinExitRecipeInterface extends Interface {
  functions: {
    BONE: TypedFunctionDescription<{ encode([]: []): string }>;

    BPOW_PRECISION: TypedFunctionDescription<{ encode([]: []): string }>;

    EXIT_FEE: TypedFunctionDescription<{ encode([]: []): string }>;

    INIT_POOL_SUPPLY: TypedFunctionDescription<{ encode([]: []): string }>;

    MAX_BOUND_TOKENS: TypedFunctionDescription<{ encode([]: []): string }>;

    MAX_BPOW_BASE: TypedFunctionDescription<{ encode([]: []): string }>;

    MAX_FEE: TypedFunctionDescription<{ encode([]: []): string }>;

    MAX_IN_RATIO: TypedFunctionDescription<{ encode([]: []): string }>;

    MAX_OUT_RATIO: TypedFunctionDescription<{ encode([]: []): string }>;

    MAX_TOTAL_WEIGHT: TypedFunctionDescription<{ encode([]: []): string }>;

    MAX_WEIGHT: TypedFunctionDescription<{ encode([]: []): string }>;

    MIN_BALANCE: TypedFunctionDescription<{ encode([]: []): string }>;

    MIN_BOUND_TOKENS: TypedFunctionDescription<{ encode([]: []): string }>;

    MIN_BPOW_BASE: TypedFunctionDescription<{ encode([]: []): string }>;

    MIN_FEE: TypedFunctionDescription<{ encode([]: []): string }>;

    MIN_WEIGHT: TypedFunctionDescription<{ encode([]: []): string }>;

    bPool: TypedFunctionDescription<{ encode([]: []): string }>;

    calcInGivenOut: TypedFunctionDescription<{
      encode([
        tokenBalanceIn,
        tokenWeightIn,
        tokenBalanceOut,
        tokenWeightOut,
        tokenAmountOut,
        swapFee
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    calcOutGivenIn: TypedFunctionDescription<{
      encode([
        tokenBalanceIn,
        tokenWeightIn,
        tokenBalanceOut,
        tokenWeightOut,
        tokenAmountIn,
        swapFee
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    calcPoolInGivenSingleOut: TypedFunctionDescription<{
      encode([
        tokenBalanceOut,
        tokenWeightOut,
        poolSupply,
        totalWeight,
        tokenAmountOut,
        swapFee
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    calcPoolOutGivenSingleIn: TypedFunctionDescription<{
      encode([
        tokenBalanceIn,
        tokenWeightIn,
        poolSupply,
        totalWeight,
        tokenAmountIn,
        swapFee
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    calcSingleInGivenPoolOut: TypedFunctionDescription<{
      encode([
        tokenBalanceIn,
        tokenWeightIn,
        poolSupply,
        totalWeight,
        poolAmountOut,
        swapFee
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    calcSingleOutGivenPoolIn: TypedFunctionDescription<{
      encode([
        tokenBalanceOut,
        tokenWeightOut,
        poolSupply,
        totalWeight,
        poolAmountIn,
        swapFee
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    calcSpotPrice: TypedFunctionDescription<{
      encode([
        tokenBalanceIn,
        tokenWeightIn,
        tokenBalanceOut,
        tokenWeightOut,
        swapFee
      ]: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    exitswapExternAmountOut: TypedFunctionDescription<{
      encode([tokenOut, tokenAmountOut]: [string, BigNumberish]): string;
    }>;

    exitswapPoolAmountIn: TypedFunctionDescription<{
      encode([tokenOut, poolAmountIn]: [string, BigNumberish]): string;
    }>;

    joinswapExternAmountIn: TypedFunctionDescription<{
      encode([_tokenIn, _tokenAmountIn, _minPoolAmountOut]: [
        string,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    joinswapPoolAmountOut: TypedFunctionDescription<{
      encode([tokenIn, poolAmountOut]: [string, BigNumberish]): string;
    }>;

    pool: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class PSingleAssetJoinExitRecipe extends Contract {
  connect(
    signerOrProvider: Signer | Provider | string
  ): PSingleAssetJoinExitRecipe;
  attach(addressOrName: string): PSingleAssetJoinExitRecipe;
  deployed(): Promise<PSingleAssetJoinExitRecipe>;

  on(
    event: EventFilter | string,
    listener: Listener
  ): PSingleAssetJoinExitRecipe;
  once(
    event: EventFilter | string,
    listener: Listener
  ): PSingleAssetJoinExitRecipe;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): PSingleAssetJoinExitRecipe;
  removeAllListeners(
    eventName: EventFilter | string
  ): PSingleAssetJoinExitRecipe;
  removeListener(
    eventName: any,
    listener: Listener
  ): PSingleAssetJoinExitRecipe;

  interface: PSingleAssetJoinExitRecipeInterface;

  functions: {
    BONE(): Promise<BigNumber>;

    BPOW_PRECISION(): Promise<BigNumber>;

    EXIT_FEE(): Promise<BigNumber>;

    INIT_POOL_SUPPLY(): Promise<BigNumber>;

    MAX_BOUND_TOKENS(): Promise<BigNumber>;

    MAX_BPOW_BASE(): Promise<BigNumber>;

    MAX_FEE(): Promise<BigNumber>;

    MAX_IN_RATIO(): Promise<BigNumber>;

    MAX_OUT_RATIO(): Promise<BigNumber>;

    MAX_TOTAL_WEIGHT(): Promise<BigNumber>;

    MAX_WEIGHT(): Promise<BigNumber>;

    MIN_BALANCE(): Promise<BigNumber>;

    MIN_BOUND_TOKENS(): Promise<BigNumber>;

    MIN_BPOW_BASE(): Promise<BigNumber>;

    MIN_FEE(): Promise<BigNumber>;

    MIN_WEIGHT(): Promise<BigNumber>;

    bPool(): Promise<string>;

    calcInGivenOut(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      tokenAmountOut: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcOutGivenIn(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      tokenAmountIn: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcPoolInGivenSingleOut(
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      poolSupply: BigNumberish,
      totalWeight: BigNumberish,
      tokenAmountOut: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcPoolOutGivenSingleIn(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      poolSupply: BigNumberish,
      totalWeight: BigNumberish,
      tokenAmountIn: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcSingleInGivenPoolOut(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      poolSupply: BigNumberish,
      totalWeight: BigNumberish,
      poolAmountOut: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcSingleOutGivenPoolIn(
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      poolSupply: BigNumberish,
      totalWeight: BigNumberish,
      poolAmountIn: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcSpotPrice(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    exitswapExternAmountOut(
      tokenOut: string,
      tokenAmountOut: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    exitswapPoolAmountIn(
      tokenOut: string,
      poolAmountIn: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    joinswapExternAmountIn(
      _tokenIn: string,
      _tokenAmountIn: BigNumberish,
      _minPoolAmountOut: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    joinswapPoolAmountOut(
      tokenIn: string,
      poolAmountOut: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    pool(): Promise<string>;
  };

  BONE(): Promise<BigNumber>;

  BPOW_PRECISION(): Promise<BigNumber>;

  EXIT_FEE(): Promise<BigNumber>;

  INIT_POOL_SUPPLY(): Promise<BigNumber>;

  MAX_BOUND_TOKENS(): Promise<BigNumber>;

  MAX_BPOW_BASE(): Promise<BigNumber>;

  MAX_FEE(): Promise<BigNumber>;

  MAX_IN_RATIO(): Promise<BigNumber>;

  MAX_OUT_RATIO(): Promise<BigNumber>;

  MAX_TOTAL_WEIGHT(): Promise<BigNumber>;

  MAX_WEIGHT(): Promise<BigNumber>;

  MIN_BALANCE(): Promise<BigNumber>;

  MIN_BOUND_TOKENS(): Promise<BigNumber>;

  MIN_BPOW_BASE(): Promise<BigNumber>;

  MIN_FEE(): Promise<BigNumber>;

  MIN_WEIGHT(): Promise<BigNumber>;

  bPool(): Promise<string>;

  calcInGivenOut(
    tokenBalanceIn: BigNumberish,
    tokenWeightIn: BigNumberish,
    tokenBalanceOut: BigNumberish,
    tokenWeightOut: BigNumberish,
    tokenAmountOut: BigNumberish,
    swapFee: BigNumberish
  ): Promise<BigNumber>;

  calcOutGivenIn(
    tokenBalanceIn: BigNumberish,
    tokenWeightIn: BigNumberish,
    tokenBalanceOut: BigNumberish,
    tokenWeightOut: BigNumberish,
    tokenAmountIn: BigNumberish,
    swapFee: BigNumberish
  ): Promise<BigNumber>;

  calcPoolInGivenSingleOut(
    tokenBalanceOut: BigNumberish,
    tokenWeightOut: BigNumberish,
    poolSupply: BigNumberish,
    totalWeight: BigNumberish,
    tokenAmountOut: BigNumberish,
    swapFee: BigNumberish
  ): Promise<BigNumber>;

  calcPoolOutGivenSingleIn(
    tokenBalanceIn: BigNumberish,
    tokenWeightIn: BigNumberish,
    poolSupply: BigNumberish,
    totalWeight: BigNumberish,
    tokenAmountIn: BigNumberish,
    swapFee: BigNumberish
  ): Promise<BigNumber>;

  calcSingleInGivenPoolOut(
    tokenBalanceIn: BigNumberish,
    tokenWeightIn: BigNumberish,
    poolSupply: BigNumberish,
    totalWeight: BigNumberish,
    poolAmountOut: BigNumberish,
    swapFee: BigNumberish
  ): Promise<BigNumber>;

  calcSingleOutGivenPoolIn(
    tokenBalanceOut: BigNumberish,
    tokenWeightOut: BigNumberish,
    poolSupply: BigNumberish,
    totalWeight: BigNumberish,
    poolAmountIn: BigNumberish,
    swapFee: BigNumberish
  ): Promise<BigNumber>;

  calcSpotPrice(
    tokenBalanceIn: BigNumberish,
    tokenWeightIn: BigNumberish,
    tokenBalanceOut: BigNumberish,
    tokenWeightOut: BigNumberish,
    swapFee: BigNumberish
  ): Promise<BigNumber>;

  exitswapExternAmountOut(
    tokenOut: string,
    tokenAmountOut: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  exitswapPoolAmountIn(
    tokenOut: string,
    poolAmountIn: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  joinswapExternAmountIn(
    _tokenIn: string,
    _tokenAmountIn: BigNumberish,
    _minPoolAmountOut: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  joinswapPoolAmountOut(
    tokenIn: string,
    poolAmountOut: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  pool(): Promise<string>;

  filters: {};

  estimate: {
    BONE(): Promise<BigNumber>;

    BPOW_PRECISION(): Promise<BigNumber>;

    EXIT_FEE(): Promise<BigNumber>;

    INIT_POOL_SUPPLY(): Promise<BigNumber>;

    MAX_BOUND_TOKENS(): Promise<BigNumber>;

    MAX_BPOW_BASE(): Promise<BigNumber>;

    MAX_FEE(): Promise<BigNumber>;

    MAX_IN_RATIO(): Promise<BigNumber>;

    MAX_OUT_RATIO(): Promise<BigNumber>;

    MAX_TOTAL_WEIGHT(): Promise<BigNumber>;

    MAX_WEIGHT(): Promise<BigNumber>;

    MIN_BALANCE(): Promise<BigNumber>;

    MIN_BOUND_TOKENS(): Promise<BigNumber>;

    MIN_BPOW_BASE(): Promise<BigNumber>;

    MIN_FEE(): Promise<BigNumber>;

    MIN_WEIGHT(): Promise<BigNumber>;

    bPool(): Promise<BigNumber>;

    calcInGivenOut(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      tokenAmountOut: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcOutGivenIn(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      tokenAmountIn: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcPoolInGivenSingleOut(
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      poolSupply: BigNumberish,
      totalWeight: BigNumberish,
      tokenAmountOut: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcPoolOutGivenSingleIn(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      poolSupply: BigNumberish,
      totalWeight: BigNumberish,
      tokenAmountIn: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcSingleInGivenPoolOut(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      poolSupply: BigNumberish,
      totalWeight: BigNumberish,
      poolAmountOut: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcSingleOutGivenPoolIn(
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      poolSupply: BigNumberish,
      totalWeight: BigNumberish,
      poolAmountIn: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    calcSpotPrice(
      tokenBalanceIn: BigNumberish,
      tokenWeightIn: BigNumberish,
      tokenBalanceOut: BigNumberish,
      tokenWeightOut: BigNumberish,
      swapFee: BigNumberish
    ): Promise<BigNumber>;

    exitswapExternAmountOut(
      tokenOut: string,
      tokenAmountOut: BigNumberish
    ): Promise<BigNumber>;

    exitswapPoolAmountIn(
      tokenOut: string,
      poolAmountIn: BigNumberish
    ): Promise<BigNumber>;

    joinswapExternAmountIn(
      _tokenIn: string,
      _tokenAmountIn: BigNumberish,
      _minPoolAmountOut: BigNumberish
    ): Promise<BigNumber>;

    joinswapPoolAmountOut(
      tokenIn: string,
      poolAmountOut: BigNumberish
    ): Promise<BigNumber>;

    pool(): Promise<BigNumber>;
  };
}
